### ISSUE TITLE
enhancement Change permission (In App)

### ISSUE THREAD

**Issue by eternia** [ducfilan/Windows-Access-Control-Manager#1]
Hi !

Thx for software it's good start ! It's possible to add In-App right modify  ?

**Comment by ducfilan** [comment]
> Hi !
> 
> Thx for software it's good start ! It's possible to add In-App right modify ?

Permissions are managed in an excel file, the structure of the template is located in this file:
https://github.com/ducfilan/Windows-Access-Control-Manager/blob/master/Template.xlsx

**Comment by ducfilan** [comment]
> Hi !
> 
> Thx for software it's good start ! It's possible to add In-App right modify ?

Now it's available. Check the new commits.
